# Generated by Django 4.1 on 2022-10-17 06:38

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_userprofile_user_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200, null=True, verbose_name='address')),
        ),
    ]
